name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer Dependencies
        run: composer install

      - name: Execute PHPCS
        run: vendor/bin/phpcs
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.3", "7.4"]
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 --default-authentication-plugin=mysql_native_password

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Install Composer Dependencies
        run: composer install

      - name: Setup Wordpress Test Database
        run: bash ./bin/install-wp-tests.sh wordpress_test root secret 127.0.0.1

      - name: Execute PHPUnit
        run: vendor/bin/phpunit